defaults:
   - ppsci_default
   - TRAIN: train_default
   - TRAIN/ema: ema_default
   - TRAIN/swa: swa_default
   - EVAL: eval_default
   - INFER: infer_default
   - hydra/job/config/override_dirname/exclude_keys: exclude_keys_default
   - _self_
hydra:
  run:
    dir: outputs_symbolic_gcn/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode}
    chdir: false
  callbacks:
    init_callback:
      _target_: ppsci.utils.callbacks.InitCallback
  sweep:
    
    dir: ${hydra.run.dir}
    subdir: ./

mode: train
seed: 42
output_dir: ${hydra:run.dir}
log_freq: 20
device: gpu


TRAIN:
  epochs: 1000
  batch_size: 32
  save_freq: 100
  eval_during_train: true
  eval_freq: 100
  checkpoint_path: null
  pretrained_model_path: null
  train_split: 0.8
  optimizer:
    learning_rate: 1e-3
    weight_decay: 1e-8
  lr_scheduler:
    name: "OneCycleLR"
    max_learning_rate: 1e-3
    final_div_factor: 1e5
  loss:
    type: "MAE"
    physics_weight: 0.0


EVAL:
  pretrained_model_path: null
  eval_with_no_grad: true
  batch_size: 32
  message_analysis:
    enabled: true


export_path: "./exported_model"

INFER:
  pretrained_model_path: null
  export_path: ./inference/ogn_model
  pdmodel_path: ./inference/ogn_model.pdmodel
  pdiparams_path: ./inference/ogn_model.pdiparams
  onnx_path: ${INFER.export_path}.onnx
  device: cpu
  engine: native
  precision: fp32
  batch_size: 1
  ir_optim: false
  min_subgraph_size: 1
  gpu_mem: 2000
  gpu_id: 0
  max_batch_size: 1024
  num_cpu_threads: 10


MODEL:
  arch: "OGN"
  input_keys: ["x", "edge_index"]
  output_keys: ["acceleration"]
  n_f: auto
  msg_dim: 100
  ndim: auto
  dt: 0.1
  hidden: 300
  aggr: "add"
  regularization_type: "l1"
  l1_strength: 1e-2

DATA:
  type: "spring"
  num_samples: 1000
  num_nodes: 6
  dimension: 2
  time_steps: 100
  time_step_size: 0.01
  downsample_factor: 5
  sample_interval: 5

DATATYPE_TYPE:
  - sim: "r1"
    dt: [5e-3]
    nt: [1000]
    n: [4, 8]
    dim: [2, 3]
  - sim: "r2"
    dt: [1e-3]
    nt: [1000]
    n: [4, 8]
    dim: [2, 3]
  - sim: "spring"
    dt: [1e-2]
    nt: [1000]
    n: [4, 8]
    dim: [2, 3]
  - sim: "string"
    dt: [1e-2]
    nt: [1000]
    n: [30]
    dim: [2]
  - sim: "charge"
    dt: [1e-3]
    nt: [1000]
    n: [4, 8]
    dim: [2, 3]
  - sim: "superposition"
    dt: [1e-3]
    nt: [1000]
    n: [4, 8]
    dim: [2, 3]
  - sim: "damped"
    dt: [2e-2]
    nt: [1000]
    n: [4, 8]
    dim: [2, 3]
  - sim: "discontinuous"
    dt: [1e-2]
    nt: [1000]
    n: [4, 8]
    dim: [2, 3]
  - sim: "string_ball"
    dt: [1e-2]
    nt: [1000]
    n: [30]
    dim: [2]