# Copyright (c) 2025 PaddlePaddle Authors. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Project information
site_name: PaddleScience Docs
site_description: An out-of-the-box open source library for scientific computing based on deep learning.
site_author: PaddlePaddle
site_url: "https://github.com/PaddlePaddle/PaddleScience"
edit_uri: edit/develop/docs/
strict: false

# Repository
repo_name: PaddleScience
repo_url: "https://github.com/PaddlePaddle/PaddleScience"

# Copyright
copyright: Copyright &copy; 2022 - 2026 PaddlePaddle

# Page tree
nav:
  - PaddleScience:
      - 主页: index.md
      - 功能介绍: overview.md
      - 安装使用: install_setup.md
      - 快速开始: quickstart.md
      - 多硬件支持: multi_device.md
      - 学习资料: tutorials.md
  - 经典案例:
    - " ":
      - 数学(AI for Math):
        - AllenCahn: examples/allen_cahn.md
        - DeepHPMs: examples/deephpms.md
        - DeepONet: examples/deeponet.md
        - Euler_Beam: examples/euler_beam.md
        - Laplace2D: examples/laplace2d.md
        - Lorenz_transform_physx: examples/lorenz.md
        - PIRBN: examples/pirbn.md
        - Rossler_transform_physx: examples/rossler.md
        - Volterra_IDE: examples/volterra_ide.md
        - NLSMB: examples/nlsmb.md
        - SPINN: examples/spinn.md
        - XPINN: examples/xpinns.md
        - NeuralOperator: examples/neuraloperator.md
        - Brusselator3D: examples/brusselator3d.md
        - Transformer4SR: examples/transformer4sr.md
        - LatentNO: examples/latent_no.md
      - 技术科学(AI for Technology):
        - 流体:
          - Fundiff: examples/fundiff.md
          - Transolver: examples/transolver.md
          - Catheter: examples/catheter.md
          - AMGNet: examples/amgnet.md
          - Aneurysm: examples/aneurysm.md
          - BubbleNet: examples/bubble.md
          - CFDGCN: examples/cfdgcn.md
          - CVit(Advection): examples/adv_cvit.md
          - CVit(NS): examples/ns_cvit.md
          - Cylinder2D_unsteady: examples/cylinder2d_unsteady.md
          - Cylinder2D_unsteady_transform_physx: examples/cylinder2d_unsteady_transformer_physx.md
          - Darcy2D: examples/darcy2d.md
          - DeepCFD: examples/deepcfd.md
          - DrivAerNet: examples/drivaernet.md
          - DrivAerNetPlusPlus: examples/drivaernetplusplus.md
          - LDC2D_steady: examples/ldc2d_steady.md
          - LDC2D_unsteady: examples/ldc2d_unsteady.md
          - Labelfree_DNN_surrogate: examples/labelfree_DNN_surrogate.md
          - NSFNets: examples/nsfnet.md
          - PhyCRNet: examples/phycrnet.md
          - ShockWave: examples/shock_wave.md
          - tempoGAN: examples/tempoGAN.md
          - NSFNet4: examples/nsfnet4.md
          - ViV: examples/viv.md
        - 结构:
          - Biharmonic2D: examples/biharmonic2d.md
          - Bracket: examples/bracket.md
          - Control_arm: examples/control_arm.md
          - EPNN: examples/epnn.md
          - Phy-LSTM: examples/phylstm.md
          - TopOpt: examples/topopt.md
          - NTopo: examples/ntopo.md
          - Heart: examples/heart.md
        - 传热:
          - Heat_Exchanger: examples/heat_exchanger.md
          - Heat_PINN: examples/heat_pinn.md
          - PhyGeoNet: examples/phygeonet.md
          - Chip_heat: examples/chip_heat.md
      - 材料科学(AI for Material):
        - hPINNs: examples/hpinns.md
        - CGCNN: examples/cgcnn.md
        - psc_NN: examples/perovskite_solar_cells_nn.md
        - Battery_LI: examples/MLP_LI.md
        - ML2DDB: examples/ml2ddb.md
        - xrdmatch: examples/xrdmatch.md
        - CNN_UTS: examples/CNN_UTS.md
      - 地球科学(AI for Earth Science):
        - KMCast: examples/kmcast.md
        - Extformer-MoE: examples/extformer_moe.md
        - FourCastNet: examples/fourcastnet.md
        - NowcastNet: examples/nowcastnet.md
        - DGMR: examples/dgmr.md
        - STAFNet: examples/stafnet.md
        - EarthFormer: examples/earthformer.md
        - MeteoFormer: examples/meteoformer.md
        - Preformer: examples/preformer.md
        - ClimateFormer: examples/climateformer.md
        - GraphCast: examples/graphcast.md
        - GenCast: examples/gencast.md
        - VelocityGAN: examples/velocity_gan.md
        - TGCN: examples/tgcn.md
        - IOPS: examples/iops.md
        - Pang-Weather: examples/pangu_weather.md
        - FengWu: examples/fengwu.md
        - FuXi: examples/fuxi.md
        - UNetFormer: examples/unetformer.md
        - WGAN_GP: examples/wgan_gp.md
        - UTAE: examples/UTAE.md
      - 化学科学(AI for Chemistry):
        - SMC Reac: examples/smc_reac.md
        - Moflow: examples/moflow.md
        - IFM: examples/ifm.md
        - Synthemol: examples/synthemol.md
        - TADF: examples/tadf.md

  - API 文档:
    - ppsci:
      - ppsci.arch: api/arch.md
      - ppsci.autodiff: api/autodiff.md
      - ppsci.constraint: api/constraint.md
      - ppsci.data:
        - ppsci.data.dataset: api/data/dataset.md
        - ppsci.data.transform: api/data/process/transform.md
        - ppsci.data.batch_transform: api/data/process/batch_transform.md
      - ppsci.equation: api/equation.md
      - ppsci.geometry: api/geometry.md
      - ppsci.loss:
        - ppsci.loss.loss: api/loss/loss.md
        - ppsci.loss.mtl: api/loss/mtl.md
      - ppsci.metric: api/metric.md
      - ppsci.optimizer:
        - ppsci.optimizer.optimizer: api/optimizer.md
        - ppsci.optimizer.lr_scheduler: api/lr_scheduler.md
      - ppsci.solver: api/solver.md
      - ppsci.utils:
        - ppsci.utils.checker: api/utils/checker.md
        - ppsci.utils.expression: api/utils/expression.md
        - ppsci.utils.initializer: api/utils/initializer.md
        - ppsci.utils.logger: api/utils/logger.md
        - ppsci.utils.misc: api/utils/misc.md
        - ppsci.utils.ema: api/utils/ema.md
        - ppsci.utils.reader: api/utils/reader.md
        - ppsci.utils.writer: api/utils/writer.md
        - ppsci.utils.save_load: api/utils/save_load.md
        - ppsci.utils.symbolic: api/utils/symbolic.md
      - ppsci.validate: api/validate.md
      - ppsci.visualize: api/visualize.md
      - ppsci.experimental: api/experimental.md
      - ppsci.probability: api/probability.md
    - deploy:
      - deploy.python_infer: api/depoly/python_infer.md
  - 使用指南: user_guide.md
  - 开发与复现指南:
    - 开发指南: development.md
    - 复现指南: reproduction.md
  - 学术成果: academic.md
  - 技术稿件: technical_doc.md
  - 共创计划: cooperation.md
  - 实训社区: https://aistudio.baidu.com/aistudio/projectoverview/public?topic=15

# Configuration
theme:
  name: material
  font:
    code: Roboto Mono
    text: Noto Serif SC
  logo: ./images/icons/paddle.png
  favicon: ./images/icons/favcion.png
  language: "zh"
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.tracking
    - navigation.sections
    # - navigation.prune # disabled temporarily for rendering speed
    - navigation.top
    - search.suggest
    - navigation.instant
    - content.code.copy
    - content.code.select
    - content.code.annotate
    - search.highlight
    - content.tabs.link
    - content.action.edit
    - content.action.view
    - content.tooltips
  icon:
    edit: material/pencil
    view: material/eye
    annotation: fontawesome/solid/circle-question
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

# Plugins
plugins:
  - include-markdown
  - search:
      lang:
        - zh
        - en
  - i18n:
      docs_structure: folder
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
        - locale: en
          name: English
          build: true
          nav_translations:
            PaddleScience: PaddleScience
            主页: Home
            功能介绍: Overview
            安装使用: Installation & Setup
            快速开始: Quick Start
            多硬件支持: Multi-Device Support
            学习资料: Tutorials
            经典案例: Classic Cases
            数学(AI for Math): Mathematics (AI for Math)
            技术科学(AI for Technology): Technology (AI for Technology)
            流体: Fluid Dynamics
            结构: Structure
            传热: Heat Transfer
            材料科学(AI for Material): Material Science (AI for Material)
            地球科学(AI for Earth Science): Earth Science (AI for Earth Science)
            化学科学(AI for Chemistry): Chemistry (AI for Chemistry)
            API 文档: API Documentation
            使用指南: User Guide
            开发与复现指南: Development & Reproduction Guide
            开发指南: Development Guide
            复现指南: Reproduction Guide
            学术成果: Academic Achievements
            技术稿件: Technical Documents
            共创计划: Collaboration Program
            实训社区: Training Community
  - glightbox
  - mkdocstrings:
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("../")
          paths: [../ppsci]
          selection:
            new_path_syntax: true
  - mkdocs-video
  - git-revision-date-localized:
      enable_creation_date: true
      fallback_to_build_date: true
      type: date
  - mike

# Extensions
markdown_extensions:
  - abbr
  - pymdownx.critic
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.snippets:
      dedent_subsections: true
  - pymdownx.arithmatex:
      generic: true
  - toc:
      permalink: true
  - pymdownx.inlinehilite
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - attr_list
  - md_in_html
  - pymdownx.tabbed:
      alternate_style: true

# Extra javascripts
extra_javascript:
  - javascripts/bd_statistics.js
  - javascripts/mathjax.js
  - javascripts/contributors.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

# Extra css
extra_css:
  - stylesheets/extra.css

# Extra
extra:
  version:
    provider: mike
    alias: true
