hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_phygeonet/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchanged
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 66
date_dir: heat_equation_bc.npz
output_dir: ${hydra:run.dir}
r: 0.5
R: 1
dtheta: 0
len_data: 2
casename: ["TemplateCase0", "TemplateCase6"]
# model settings
MODEL:
  input_keys: [ 'coords' ]
  output_keys: [ 'outputV' ]
  hidden_size: [16, 32, 16]
  h: 0.01
  ny: 276
  nx: 49
  nVarIn: 1
  nVarOut: 1
  padSingleSide: 1

# training settings
TRAIN:
  epochs: 2000
  eval_with_no_grad: true
  lr: 1e-3
  batchsize: 2

# evaluation settings
EVAL:
  pretrained_model_path: ./checkpoints/latest
  eval_with_no_grad: true
