defaults:
  - ppsci_default
  - TRAIN: train_default
  - TRAIN/ema: ema_default
  - TRAIN/swa: swa_default
  - EVAL: eval_default
  - INFER: infer_default
  - hydra/job/config/override_dirname/exclude_keys: exclude_keys_default
  - _self_

hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_era5_land_ukb/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
  callbacks:
    init_callback:
      _target_: ppsci.utils.callbacks.InitCallback
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 42
output_dir: ${hydra:run.dir}
log_freq: 1

DATA_DIR: ./data/

# model settings
MODEL:
  input_keys: ["video", "vec"]
  output_keys: ["y"]
  T: 12
  H: 10
  W: 10
  C: 10
  N: 24

# training settings
TRAIN:
  epochs: 2
  iters_per_epoch: 95
  save_freq: 1
  eval_during_train: false
  eval_freq: 5
  weight_decay: 1.0e-5
  batch_size: 32
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  pretrained_model_path: null

# inference settings
INFER:
  max_batch_size: 128
  batch_size: 32
