defaults:
  - ppsci_default
  - TRAIN: train_default
  - TRAIN/ema: ema_default
  - TRAIN/swa: swa_default
  - EVAL: eval_default
  - INFER: infer_default
  - hydra/job/config/override_dirname/exclude_keys: exclude_keys_default
  - _self_

hydra:
  run:
    # dynamic output directory according to running time and override name
    # dir: outputs_confild_case1/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
    dir: ./outputs_un_confild_case2
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
  callbacks:
    init_callback:
      _target_: ppsci.utils.callbacks.InitCallback
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: eval # running mode: infer
seed: 2025
output_dir: ${hydra:run.dir}
log_freq: 20

TRAIN:
  batch_size : 16
  test_batch_size : 16
  ema_rate: "0.9999"
  lr_anneal_steps: 0
  lr : 5.e-5
  weight_decay: 0.0
  final_lr: 0.
  microbatch: -1

EVAL:
  mutil_GPU: 1
  lr : 5.e-5
  ema_rate: "0.9999"
  log_interval: 1000
  save_interval: 10000
  lr_anneal_steps: 0
  time_length : 256
  latent_length : 256

UNET:
  image_size : 256
  num_channels: 128
  num_res_blocks: 2
  num_heads: 4
  num_head_channels: 64
  attention_resolutions: "32,16,8"
  channel_mult: null
  ema_path: /home/aistudio/work/extracted/data/Case2/diffusion/ema.pdparams

Diff:
  steps: 1000
  noise_schedule: "cosine"

CNF:
  mutil_GPU: 1
  data_path: /home/aistudio/work/extracted/data/Case2/data.npy
  # coor_path: ../Case2/coords.npy
  load_data_fn: load_channel_flow
  normalizer:
    method: "-11"
    dim: 0
  CONFILD:
    input_keys: ["confild_x", "latent_z"]
    output_keys: ["confild_output"]
    num_hidden_layers: 10
    out_features: 4
    hidden_features: 256
    in_coord_features: 2
    in_latent_features: 256
  normalizer_params_path: /home/aistudio/work/extracted/data/Case2/cnf/normalizer_params.pdparams
  model_path: ./outputs_confild_case2/confild_case2/epoch_99999

DATA:
  max_val: 1.0
  min_val: -1.0
  train_data: "/home/aistudio/work/extracted/data/Case2/train_data.npy"
  valid_data: "/home/aistudio/work/extracted/data/Case2/valid_data.npy"