hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_VIV/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 42
output_dir: ${hydra:run.dir}
log_freq: 20


# model settings
MODEL:
  input_keys: ["t_f"]
  output_keys: ["eta"]
  num_layers: 5
  hidden_size: 50
  activation: "tanh"

# training settings
TRAIN:
  epochs: 100000
  eval_freq: 1000
  iters_per_epoch: 1
  save_freq: 1
  eval_during_train: true
  optimizer:
    epochs: 100000
    iters_per_epoch: 1
    learning_rate: 0.001
    step_size: 20000
    gamma: 0.9
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  pretrained_model_path: null
