data:
  datapath: 'data/NS_fine_Re200_T128_part0.npy'
  datapath2: 'data/NS_fine_Re200_T128_part1.npy'
  Re: 200
  total_num: 100
  offset: 0
  n_sample: 200
  time_interval: 1.0
  nx: 128
  nt: 128
  sub: 1
  sub_t: 2
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128

train:
  batchsize: 1
  epochs: 150
  milestones: [25, 50, 75, 100]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 1.0
  f_loss: 1.0
  xy_loss: 5.0
  save_dir: 'Re200-FDM'
  save_name: 'PINO-pretrain-Re200-1s.pt'

log:
  project: 'PINO-pretrain'
  group: 'Re200-1s-tanh'


