hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_euler_beam/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 42
output_dir: ${hydra:run.dir}
log_freq: 20
to_static: false

# set working condition
q: -1.0
D: 1.0

# model settings
MODEL:
  input_keys: ["x"]
  output_keys: ["u"]
  num_layers: 3
  hidden_size: 20

# training settings
TRAIN:
  epochs: 10000
  iters_per_epoch: 1
  save_freq: 20
  eval_during_train: true
  eval_freq: 1000
  learning_rate: 1e-3
  batch_size:
    pde: 16
    bc: 4
  weight:
    bc_back: {"u": 10, "v": 10, "w": 10}
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  pretrained_model_path: null
  eval_with_no_grad: true
  total_size: 100
  batch_size:
    sup_validator: 128
