hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_phygeonet/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchanged
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 66
date_dir: ./heat_equation.npz
output_dir: ${hydra:run.dir}
boundary_dir: TemplateCase/30/C
dtheta: 0

len_data: 1
# model settings
MODEL:
  input_keys: [ 'coords' ]
  output_keys: [ 'outputV' ]
  h: 0.01
  ny: 19
  nx: 84
  NvarInput: 2
  NvarOutput: 1
  padSingleSide: 1

# training settings
TRAIN:
  epochs: 1000
  eval_with_no_grad: true
  lr: 1e-3
  batchsize: 1

# evaluation settings
EVAL:
  pretrained_model_path: null
  eval_with_no_grad: true
