hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_phygeonet/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  callbacks:
    init_callback:
      _target_: ppsci.utils.callbacks.InitCallback
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 66
data_dir: ./data/heat_equation.npz
output_dir: ${hydra:run.dir}
dtheta: 0
epochs: 1500

# model settings
MODEL:
  input_keys: [ 'coords' ]
  output_keys: [ 'output_v' ]
  hidden_size: [16, 32, 16]
  h: 0.01
  ny: 19
  nx: 84
  nvar_in: 2
  nvar_out: 1
  pad_singleside: 1

# training settings
TRAIN:
  learning_rate: 1e-3
  batch_size: 1

# evaluation settings
EVAL:
  pretrained_model_path: null
  eval_with_no_grad: true
