data:
  datapath: 'data/NS_fine_Re100_T128_part2.npy'
  Re: 100
  total_num: 100
  offset: 0
  n_sample: 1
  time_interval: 1.0
  nx: 128
  nt: 128
  sub: 1
  sub_t: 2
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128

train:
  batchsize: 1
  epochs: 8000
  milestones: [1000, 2000, 3000, 4000, 5000, 6000, 7000]
  base_lr: 0.0025
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 0.0
  save_dir: 'Re100-FDM'
  save_name: 'PINO-Re100-1s.pt'
  ckpt: 'checkpoints/Re400-FDM/PINO-pretrain-Re400-1s.pt'

log:
  project: 'PINO-transfer-tanh'
  group: 'Re400to100-1s'


