data:
  datapath: 'data/NS_fine_Re500_s2048_T100.npy'
  Re: 500
  total_num: 100
  offset: 300
  n_sample: 1
  time_interval: 0.5
  nx: 256
  nt: 128
  sub: 2
  sub_t: 1
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128

train:
  batchsize: 1
  epochs: 8000
  milestones: [1000, 2000, 3000, 4000, 5000, 6000]
  base_lr: 0.0025
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 0.0
  save_dir: 'Re500-FDM'
  save_name: 'PINO-Re500-05.pt'
  ckpt: 'checkpoints/Re500-FDM/pretrain-Re500-05s-4000.pt'

log:
  project: 'PINO-Re500-exp'
  group: 'Re500to500-128-4k-all'



