defaults: #
  - ppsci_default #
  - TRAIN: train_default #
  - EVAL: eval_default #
#  - INFER: infer_default #
  - _self_ #

hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_Est/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname} #
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
  callbacks:
    init_callback: #
      _target_: ppsci.utils.callbacks.InitCallback #
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: eval # running mode: train/eval #
seed: 42 #
output_dir: ${hydra:run.dir} #
log_freq: 20 #
use_tbd: false #
VIV_DATA_PATH: "./f.dat" #

# model settings
MODEL: #
#  input_keys: tuple(x.keys()) #
  output_keys: ["u"] #
#  num_layers: None #
#  hidden_size:
#    - 587
#    - 256 #
  activation: "relu" #
  dropout: 0.5

# training settings
TRAIN: #
  epochs: 200 #
  iters_per_epoch: 20 #
  save_freq: 100 #
  eval_during_train: False #
  batch_size: 8 #
  learning_rate: 0.0001
  save_model_path: './est_model.pth'
  weight_decay: 1e-5
  pretrained_model_path: null #
  checkpoint_path: null #
  k: 9
  i: 2

# evaluation settings
EVAL:
  test_size: 0.1
  load_model_path: './est_model.pth'
  seed: 20
#  pretrained_model_path: null #
#  batch_size: 32 #

# inference settings
#INFER: #
#  pretrained_model_path: "https://github.com/YfB1125/PaddleScience/blob/dev_model/TADF/f/output/checkpoints/latest.pdparams" #
#  export_path: ./inference/viv #
#  pdmodel_path: ${INFER.export_path}.pdmodel #
#  pdiparams_path: ${INFER.export_path}.pdiparams #
#  input_keys: ${MODEL.input_keys} #
#  output_keys: ["u"]  #
#  device: cpu #
#  engine: native #
#  precision: fp32 #
#  ir_optim: true #
#  min_subgraph_size: 10 #
#  gpu_mem: 4000 #
#  gpu_id: 0 #
#  max_batch_size: 64 #
#  num_cpu_threads: 4 #
#  batch_size: 16 #
