hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_dgmr/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: eval # running mode: train/eval
seed: 42
output_dir: ${hydra:run.dir}

# dataset settings
DATASET:
  split: validation # train or validation
  NUM_INPUT_FRAMES: 4
  NUM_TARGET_FRAMES: 18
  dataset_path: /workspace/workspace/skillful_nowcasting/openclimatefix/nimrod-uk-1km
  number: 10

# dataLoader settings
DATALOADER:
  batch_size: 1
  shuffle: False
  num_workers: 1
  drop_last: True

# model settings
MODEL:
  forecast_steps: 18
  input_channels: 1
  output_shape: 256
  gen_lr: 5e-05
  disc_lr: 0.0002
  visualize: False
  conv_type: 'standard'
  num_samples: 6
  grid_lambda: 20.0
  beta1: 0.0
  beta2: 0.999
  latent_channels: 768
  context_channels: 384
  generation_steps: 6

# evaluation settings
EVAL:
  pretrained_model_path: /workspace/workspace/skillful_nowcasting/openclimatefix/paddle/paddle_model.pdparams
