hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_hpinns/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchanged
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 42
output_dir: ${hydra:run.dir}
DATASET_PATH: ./datasets/hpinns_holo_train.mat
DATASET_PATH_VALID: ./datasets/hpinns_holo_valid.mat

# set working condition
TRAIN_MODE: aug_lag  # "soft", "penalty", "aug_lag"
TRAIN_K: 9

# model settings
MODEL:
  re_net:
    output_keys: ["e_re"]
    num_layers: 4
    hidden_size: 48
    activation: "tanh"
  im_net:
    output_keys: ["e_im"]
    num_layers: 4
    hidden_size: 48
    activation: "tanh"
  eps_net:
    output_keys: ["eps"]
    num_layers: 4
    hidden_size: 48
    activation: "tanh"

# training settings
TRAIN:
  epochs: 20000
  iters_per_epoch: 1
  eval_during_train: false
  learning_rate: 0.001
  max_iter: 15000
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  pretrained_model_path: null
