data:
  datapath: 'data/NS_Re500_s256_T100_test.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 1
  time_interval: 0.5
  nx: 256
  nt: 128
  sub: 2
  sub_t: 1
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128

train:
  batchsize: 1
  epochs: 6000
  milestones: [1000, 3000, 5000]
  base_lr: 0.0025
  beta1: 0.9
  beta2: 0.999
  scheduler_gamma: 0.5
  ic_loss: 5.0
  f_loss: 1.0
  xy_loss: 0
  save_dir: 'Re500'
  save_name: 'PINO-fintune-05s.pt'
  ckpt: 'checkpoints/Re500-FDM/PINO-pretrain-Re500-05s-4k1k.pt'
  twolayer: True

log:
  project: 'PINO-Re500-ICLR'
  group: 'Re500-finetune-128-4k1-2layer'


