hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_schrodinger/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working directory unchanged
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 42
output_dir: ${hydra:run.dir}
DATASET_PATH: ./datasets/NLS.mat
DATASET_PATH_SOL: ./datasets/NLS.mat

# set working condition
T_LB: 0.0
T_UB: 2.0
X_LB: -5.0
X_UB: 5.0

# model settings
MODEL:
  idn_u_net:
    input_keys: ["t", "x"]
    output_keys: ["u_idn"]
    num_layers: 4
    hidden_size: 50
    activation: "sin"
  idn_v_net:
    input_keys: ["t", "x"]
    output_keys: ["v_idn"]
    num_layers: 4
    hidden_size: 50
    activation: "sin"
  pde_f_net:
    input_keys: ["u", "v", "du_x", "dv_x", "du_xx", "dv_xx"]
    output_keys: ["f_pde"]
    num_layers: 2
    hidden_size: 100
    activation: "sin"
  pde_g_net:
    input_keys: ["u", "v", "du_x", "dv_x", "du_xx", "dv_xx"]
    output_keys: ["g_pde"]
    num_layers: 2
    hidden_size: 100
    activation: "sin"

# training settings
TRAIN:
  epochs: 50000
  iters_per_epoch: 1
  max_iter: 50000  # for LBFGS
  learning_rate: 1.0e-4
  batch_size:
    eval: 10000
  eval_during_train: false
  pretrained_model_path: null
  checkpoint_path: null

# evaluation settings
EVAL:
  pretrained_model_path: null
