data:
  datapath: 'data/ns_V1e-3_N5000_T50.mat'
  vis: 0.001
  total_num: 5000
  offset: 4900
  n_sample: 1
  time_scale: 49
  nx: 64
  nt: 50
  sub: 1      # not used here
  sub_t: 1    # not used here
  shuffle: True

model:
  layers: [3, 50, 50, 50, 50, 50, 50, 3]
  activation: LAAF-10 tanh

train:
  batchsize: 1
  epochs: 5000
  milestones: [1000, 1500, 2000]
  base_lr: 0.001
  num_domain: 10000
  num_boundary: 18000
  num_test: 100
  log_step: 100

log:
  logfile: 'log/pinns-50s-laaf.csv'