data:
  datapath: 'data/NS_Re500_s256_T100_test.npy'
  Re: 500
  total_num: 100
  offset: 0
  n_sample: 1
  time_interval: 0.5
  nx: 256
  nt: 128
  sub: 2
  sub_t: 1
  shuffle: True

model:
  layers: [3, 50, 50, 50, 50, 50, 50, 3]
  activation: tanh

train:
  batchsize: 1
  epochs: 3000
  milestones: [1000, 1500, 2000]
  base_lr: 0.01
  num_domain: 5000
  num_boundary: 10000
  num_test: 100
  log_step: 100

log:
  project: 'PINO-Re500-ICLR'
  group: 'Re500-PINNs'
  logfile: 'log/pinns128-plot.csv'



