# general settings
mode: train # running mode: train/eval
seed: 66
output_dir: ./output_case1
boundary_dir: TemplateCase/30/C

lr: 1e-3
dtheta: 0
batchsize: 1
# model settings
MODEL:
  input_keys: [ 'coords' ]
  output_keys: [ 'outputV' ]
  h: 0.01
  ny: 19
  nx: 84
  NvarInput: 2
  NvarOutput: 1
  padSingleSide: 1

# training settings

epochs: 1500
eval_with_no_grad: true

# evaluation settings
EVAL:
  pretrained_model_path: null
  eval_with_no_grad: true
