### base config ###
full_field: &FULL_FIELD
  loss: "l2"
  lr: 1E-3
  scheduler: "ReduceLROnPlateau"
  num_data_workers: 0
  dt: 1 # how many timesteps ahead the model will predict
  n_history: 0 #how many previous timesteps to consider
  prediction_type: "iterative"
  prediction_length: 41 #applicable only if prediction_type == "iterative"
  n_initial_conditions: 5 #applicable only if prediction_type == "iterative"
  ics_type: "default"
  save_raw_forecasts: !!bool True
  save_channel: !!bool False
  masked_acc: !!bool False
  maskpath: None
  perturb: !!bool False
  add_grid: !!bool False
  N_grid_channels: 0
  gridtype: "sinusoidal" #options "sinusoidal" or "linear"
  roll: !!bool False
  max_epochs: 50
  batch_size: 8

  #afno hyperparams
  num_blocks: 8
  nettype: "afno"
  patch_size: 8
  width: 56
  modes: 32
  #options default, residual
  target: "default" 
  in_channels: [0,1]
  out_channels: [0,1] #must be same as in_channels if prediction_type == "iterative"
  normalization: "zscore" #options zscore (minmax not supported) 
  train_data_path: "era5/train"
  valid_data_path: "era5/test" #"../afs_era5/test" #
  inf_data_path: "era5/out_of_sample" # test set path for inference
  exp_dir: "output"
  time_means_path:   "era5/stat/time_means.npy"
  global_means_path: "era5/stat/global_means.npy"
  global_stds_path:  "era5/stat/global_stds.npy"

  orography: !!bool False
  orography_path: None

  log_to_screen: !!bool True
  save_checkpoint: !!bool True

  enable_nhwc: !!bool False
  optimizer_type: "Adam"
  crop_size_x: None
  crop_size_y: None

  two_step_training: !!bool False
  plot_animations: !!bool False

  add_noise: !!bool False
  noise_std: 0

afno_backbone: &backbone
  <<: *FULL_FIELD
  lr: 5E-4
  batch_size: 1
  max_epochs: 150
  scheduler: "CosineAnnealingLR"
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  out_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  orography: !!bool False
  orography_path: None 

afno_backbone_finetune: 
  <<: *backbone
  lr: 1E-4
  batch_size: 1
  max_epochs: 50
  pretrained: !!bool True
  two_step_training: !!bool True
  pretrained_ckpt_path: "output/afno_backbone_paddle/00/training_checkpoints/best_ckpt.tar"

### PRECIP ###
precip: &precip
  <<: *backbone
  in_channels: [0, 1 ,2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]
  out_channels: [0]
  nettype: "afno"
  nettype_wind: "afno"
  lr: 2.5E-4
  batch_size: 1
  max_epochs: 25
  precip: "era5/precip"
  time_means_path_tp: "era5/stat/precip/time_means.npy"
  model_wind_path: "output/afno_backbone_finetune_paddle/00/training_checkpoints/best_ckpt.tar" # 
  precip_eps: !!float 1e-5
  prediction_length: 20 #applicable only if prediction_type == "iterative"
