# general settings
mode: train # running mode: train/infer
seed: 42

# training settings
run_name: r0
use_ddp: False
config: pois-64-pretrain-e1_20_m3
yaml_config: config/operators_poisson.yaml
sweep_id: ''

# evaluation settings
infer_config: config/inference_poisson.yaml
ckpt_path: data/pd_finetune_b01_m0_n8192.tar
num_demos: 1
tqdm: False
save_pred: False
