mode: "train"
seed: 42
device: "cpu"
data:
  train_path: "./Dataset/Train_val"
  test_path: "./Dataset/Test"
  N: 1
train:
  epochs: 32
  n_splits: 5
  batch_size: 32
  lr: 0.0009761248347350309
output_dir: "./Saved_Output"
