hydra:
  run:
    # dynamic output directory according to running time and override name
    dir: outputs_control_arm/forward/${now:%Y-%m-%d}/${now:%H-%M-%S}/${hydra.job.override_dirname}
  job:
    name: ${mode} # name of logfile
    chdir: false # keep current working direcotry unchaned
    config:
      override_dirname:
        exclude_keys:
          - TRAIN.checkpoint_path
          - TRAIN.pretrained_model_path
          - EVAL.pretrained_model_path
          - mode
          - output_dir
          - log_freq
  sweep:
    # output directory for multirun
    dir: ${hydra.run.dir}
    subdir: ./

# general settings
mode: train # running mode: train/eval
seed: 2023
output_dir: ${hydra:run.dir}
log_freq: 100

# set working condition
NU: 0.3
E: 1
T: [0, 0, 0.0025]   # +Z axis
# T: [-0.0025, 0, 0]  # -X axis

# set geometry file path
GEOM_PATH: ./datasets/control_arm.stl

# set geometry parameter
CIRCLE_LEFT_CENTER_XY: [-4.4, 0]
CIRCLE_LEFT_RADIUS: 1.65
CIRCLE_RIGHT_CENTER_XZ: [15.8, 0]
CIRCLE_RIGHT_RADIUS: 2.21

# model settings
MODEL:
  disp_net:
    input_keys: ["x", "y", "z"]
    output_keys: ["u", "v", "w"]
    num_layers: 6
    hidden_size: 512
    activation: "silu"
    weight_norm: true
  stress_net:
    input_keys: ["x", "y", "z"]
    output_keys: ["sigma_xx", "sigma_yy", "sigma_zz", "sigma_xy", "sigma_xz", "sigma_yz"]
    num_layers: 6
    hidden_size: 512
    activation: "silu"
    weight_norm: true

# training settings
TRAIN:
  epochs: 2000
  iters_per_epoch: 1000
  save_freq: 100
  eval_during_train: false
  eval_freq: 100
  lr_scheduler:
    epochs: ${TRAIN.epochs}
    iters_per_epoch: ${TRAIN.iters_per_epoch}
    learning_rate: 4.0e-5
    gamma: 0.95
    decay_steps: 15000
    by_epoch: false
  batch_size:
    arm_left: 128
    arm_right: 256
    arm_surface: 4096
    arm_interior: 2048
    visualizer_vtu: 100000
  weight:
    arm_right: {"u": 100, "v": 100, "w": 100}
  pretrained_model_path: null
  checkpoint_path: null
  enable_parallel: false # whether to enable parallel training

# evaluation settings
EVAL:
  pretrained_model_path: null
