data:
  name: KF
  paths: ['/raid/hongkai/NS-Re500_T300_id0-shuffle.npy']
  Re: 500
  offset: 0
  total_num: 300
  raw_res: [256, 256, 513]
  n_data_samples: 25
  data_res: [128, 128, 257]  # resolution in 1 second
  pde_res: [128, 128, 257]   # resolution in 1 second
  a_offset: 0
  n_a_samples: 250
  testoffset: 250
  n_test_samples: 25
  t_duration: 0.125
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  act: gelu
  num_pad: 4
  pad_ratio: [0, 0.125]

train:
  batchsize: 1
  epochs: 201
  num_iter: 50_001
  milestones: [20_000, 40_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_step: 5000
  eval_step: 5000

test:
  batchsize: 1
  data_res: [256, 256, 513]
  ckpt: model-400.pt

log:
  logdir: Re500-1_8s-dat200-FNO
  entity: hzzheng-pino
  project: PINO-KF-Re500
  group: Re500-1_8s-dat200-FNO
