data:
  paths: ['../data/NS-T4000.npy']
  Re: 500
  total_num: 4000
  offset: 0
  n_samples: 3200
  t_duration: 1.0
  data_res: [64, 64, 65]
  pde_res: [128, 128, 65]
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  act: gelu
  num_pad: 4

train:
  batchsize: 2
  epochs: 501
  milestones: [300]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_step: 100

log:
  logdir: Re500-1s-FNO
  entity: hzzheng-pino
  project: 'PINO-NS'
  group: 'Re500-1s-FNO'
