data:
  paths: ['../data/NS-Re500Part0.npy', '../data/NS-Re500Part1.npy']
  Re: 500
  total_num: 200
  offset: 0
  n_samples: 700
  t_duration: 0.5
  data_res: [64, 64, 33]
  pde_res: [128, 128, 65]
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  act: gelu
  num_pad: 4

train:
  batchsize: 2
  epochs: 501
  milestones: [300]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 0.0
  f_loss: 0.0
  xy_loss: 1.0
  save_step: 100

test:
  batchsize: 1
  data_res: [128, 128, 65]
  ckpt: model-500.pt

log:
  logdir: Re500-05s-FNO
  entity: hzzheng-pino
  project: 'PINO-NS'
  group: 'Re500-05s-FNO'
