data:
  name: KF
  paths: ['../data/NS-Re500_T300_id0.npy']
  Re: 500
  offset: 0
  total_num: 300
  raw_res: [256, 256, 513]
  n_data_samples: 200
  data_res: [64, 64, 257]  # resolution in 1 second
  pde_res: [256, 256, 513]   # resolution in 1 second
  a_offset: 0
  n_a_samples: 250
  testoffset: 200
  n_test_samples: 50
  t_duration: 0.125
  shuffle: True

model:
  layers: [64, 64, 64, 64, 64]
  modes1: [8, 8, 8, 8]
  modes2: [8, 8, 8, 8]
  modes3: [8, 8, 8, 8]
  fc_dim: 128
  act: gelu
  num_pad: 4
  pad_ratio: 0.0625

train:
  batchsize: 2
  epochs: 201
  num_iter: 200_001
  milestones: [20_000, 70_000, 120_000]
  base_lr: 0.001
  scheduler_gamma: 0.5
  ic_loss: 1.0
  f_loss: 1.0
  xy_loss: 5.0
  save_step: 5000
  eval_step: 5000

test:
  batchsize: 1
  data_res: [64, 64, 257]
  ckpt: model-400.pt

log:
  logdir: Re500-1_8s-pde2k-dat16-PINO
  entity: hzzheng-pino
  project: PINO-NS
  group: Re500-1_8s-pde2k-dat16-PINO
