name: ci
on:
  push:
    branches:
      - develop
      - release/1.0
      - release/1.1
      - release/1.2
      - release/1.2.1
      - ai4s_universal_platform
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - uses: actions/setup-python@v5
        with:
          python-version: 3.9
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-
      - run: pip install -r docs/requirements.txt
      - run: mkdocs gh-deploy --force

      - name: Deploy documentation
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # 获取当前分支名称
          BRANCH=$(git rev-parse --abbrev-ref HEAD)

          # 根据分支名称部署相应的文档版本
          if [ "$BRANCH" == "deploy_in_gitpage" ]; then
            ALIAS_VERSION="latest"
            mike deploy --push --update-aliases $ALIAS_VERSION
          elif [ "$BRANCH" == "release/1.2" ]; then
            ALIAS_VERSION="release-1.2"
            mike deploy --push --update-aliases $ALIAS_VERSION
          elif [ "$BRANCH" == "release/1.1" ]; then
            ALIAS_VERSION="release-1.1"
            mike deploy --push --update-aliases $ALIAS_VERSION
          elif [ "$BRANCH" == "release/1.0" ]; then
            ALIAS_VERSION="release-1.0"
            mike deploy --push --update-aliases $ALIAS_VERSION
          elif [ "$BRANCH" == "ai4s_universal_platform" ]; then
            ALIAS_VERSION="ai4s_universal_platform"
            mike deploy --push --update-aliases $ALIAS_VERSION
          fi

          mike set-default --push latest
